import React, {useEffect, useState} from 'react';
import {Button} from 'antd';
import {useMappedState} from "redux-react-hook";
import WeekIncrease from '../../components/DataFiltering/WeekIncrease';
import {outliers, insertData} from '../../components/DataFiltering/DataFiltering';
import {diffValueOfPrice} from '../../components/utils/index';
const mapState = (state) => {
    return ({
        shanghai: state.main.shanghai,
        weekIncreaseShanghai: state.main.weekIncreaseShangHai,
    });
};

export default function CityShangHai(props) {
    const [administrative, setAdministrativeByChoice] = useState('');
    const {shanghai, weekIncreaseShanghai} = useMappedState(mapState);


    const [pureFlood, setPureFlood] = useState([{"administrative": "临港新城", "datasSring": "datasSring", "data": []},
    {"administrative": "泥城镇", "datasSring": "datasSring", "data": []},
    {"administrative": "万祥镇", "datasSring": "datasSring", "data": []},
    {"administrative": "高东", "datasSring": "datasSring", "data": []},
    {"administrative": "大团镇", "datasSring": "datasSring", "data": []},
    {"administrative": "周浦", "datasSring": "datasSring", "data": []},
    {"administrative": "塘桥", "datasSring": "datasSring", "data": []},
    {"administrative": "金桥", "datasSring": "datasSring", "data": []},
    {"administrative": "北蔡", "datasSring": "datasSring", "data": []},
    {"administrative": "川沙", "datasSring": "datasSring", "data": []},
    {"administrative": "惠南", "datasSring": "datasSring", "data": []},
    {"administrative": "外高桥", "datasSring": "datasSring", "data": []},
    {"administrative": "航头", "datasSring": "datasSring", "data": []},
    {"administrative": "御桥", "datasSring": "datasSring", "data": []},
    {"administrative": "源深", "datasSring": "datasSring", "data": []},
    {"administrative": "杨东", "datasSring": "datasSring", "data": []},
    {"administrative": "三林", "datasSring": "datasSring", "data": []},
    {"administrative": "潍坊", "datasSring": "datasSring", "data": []},
    {"administrative": "洋泾", "datasSring": "datasSring", "data": []},
    {"administrative": "世博", "datasSring": "datasSring", "data": []},
    {"administrative": "金杨", "datasSring": "datasSring", "data": []},
    {"administrative": "碧云", "datasSring": "datasSring", "data": []},
    {"administrative": "张江", "datasSring": "datasSring", "data": []},
    {"administrative": "曹路", "datasSring": "datasSring", "data": []},
    {"administrative": "宣桥", "datasSring": "datasSring", "data": []},
    {"administrative": "高行", "datasSring": "datasSring", "data": []},
    {"administrative": "新场", "datasSring": "datasSring", "data": []},
    {"administrative": "曹杨", "datasSring": "datasSring", "data": []},
    {"administrative": "长征", "datasSring": "datasSring", "data": []},
    {"administrative": "真光", "datasSring": "datasSring", "data": []},
    {"administrative": "真如", "datasSring": "datasSring", "data": []},
    {"administrative": "桃浦", "datasSring": "datasSring", "data": []},
    {"administrative": "甘泉宜川", "datasSring": "datasSring", "data": []},
    {"administrative": "老闵行", "datasSring": "datasSring", "data": []},
    {"administrative": "莘庄", "datasSring": "datasSring", "data": []},
    {"administrative": "华漕", "datasSring": "datasSring", "data": []},
    {"administrative": "金虹桥", "datasSring": "datasSring", "data": []},
    {"administrative": "梅陇", "datasSring": "datasSring", "data": []},
    {"administrative": "古美", "datasSring": "datasSring", "data": []},
    {"administrative": "七宝", "datasSring": "datasSring", "data": []},
    {"administrative": "颛桥", "datasSring": "datasSring", "data": []},
    {"administrative": "浦江", "datasSring": "datasSring", "data": []},
    {"administrative": "马桥", "datasSring": "datasSring", "data": []},
    {"administrative": "春申", "datasSring": "datasSring", "data": []},
    {"administrative": "龙柏", "datasSring": "datasSring", "data": []},
    {"administrative": "金汇", "datasSring": "datasSring", "data": []},
    {"administrative": "安亭", "datasSring": "datasSring", "data": []},
    {"administrative": "嘉定新城", "datasSring": "datasSring", "data": []},
    {"administrative": "南翔", "datasSring": "datasSring", "data": []},
    {"administrative": "江桥", "datasSring": "datasSring", "data": []},
    {"administrative": "嘉定老城", "datasSring": "datasSring", "data": []},
    {"administrative": "丰庄", "datasSring": "datasSring", "data": []},
    {"administrative": "康桥", "datasSring": "datasSring", "data": []},
    {"administrative": "陆家嘴", "datasSring": "datasSring", "data": []},
    {"administrative": "南码头", "datasSring": "datasSring", "data": []},
    {"administrative": "祝桥", "datasSring": "datasSring", "data": []},
    {"administrative": "周家嘴路", "datasSring": "datasSring", "data": []},
    {"administrative": "控江路", "datasSring": "datasSring", "data": []},
    {"administrative": "东外滩", "datasSring": "datasSring", "data": []},
    {"administrative": "中原", "datasSring": "datasSring", "data": []},
    {"administrative": "鞍山", "datasSring": "datasSring", "data": []},
    {"administrative": "黄兴公园", "datasSring": "datasSring", "data": []},
    {"administrative": "新江湾城", "datasSring": "datasSring", "data": []},
    {"administrative": "五角场", "datasSring": "datasSring", "data": []},
    {"administrative": "唐镇", "datasSring": "datasSring", "data": []},
    {"administrative": "淞宝", "datasSring": "datasSring", "data": []},
    {"administrative": "张庙", "datasSring": "datasSring", "data": []},
    {"administrative": "顾村", "datasSring": "datasSring", "data": []},
    {"administrative": "罗店", "datasSring": "datasSring", "data": []},
    {"administrative": "月浦", "datasSring": "datasSring", "data": []},
    {"administrative": "淞南", "datasSring": "datasSring", "data": []},
    {"administrative": "大场镇", "datasSring": "datasSring", "data": []},
    {"administrative": "通河", "datasSring": "datasSring", "data": []},
    {"administrative": "新华路", "datasSring": "datasSring", "data": []},
    {"administrative": "古北", "datasSring": "datasSring", "data": []},
    {"administrative": "中山公园", "datasSring": "datasSring", "data": []},
    {"administrative": "西郊", "datasSring": "datasSring", "data": []},
    {"administrative": "北新泾", "datasSring": "datasSring", "data": []},
    {"administrative": "仙霞", "datasSring": "datasSring", "data": []},
    {"administrative": "镇宁路", "datasSring": "datasSring", "data": []},
    {"administrative": "虹桥", "datasSring": "datasSring", "data": []},
    {"administrative": "斜土路", "datasSring": "datasSring", "data": []},
    {"administrative": "龙华", "datasSring": "datasSring", "data": []},
    {"administrative": "康健", "datasSring": "datasSring", "data": []},
    {"administrative": "建国西路", "datasSring": "datasSring", "data": []},
    {"administrative": "徐家汇", "datasSring": "datasSring", "data": []},
    {"administrative": "长桥", "datasSring": "datasSring", "data": []},
    {"administrative": "植物园", "datasSring": "datasSring", "data": []},
    {"administrative": "万体馆", "datasSring": "datasSring", "data": []},
    {"administrative": "衡山路", "datasSring": "datasSring", "data": []},
    {"administrative": "田林", "datasSring": "datasSring", "data": []},
    {"administrative": "上海南站", "datasSring": "datasSring", "data": []},
    {"administrative": "华泾", "datasSring": "datasSring", "data": []},
    {"administrative": "华东理工", "datasSring": "datasSring", "data": []},
    {"administrative": "南桥", "datasSring": "datasSring", "data": []},
    {"administrative": "海湾", "datasSring": "datasSring", "data": []},
    {"administrative": "奉城", "datasSring": "datasSring", "data": []},
    {"administrative": "西渡", "datasSring": "datasSring", "data": []},
    {"administrative": "奉贤金汇", "datasSring": "datasSring", "data": []},
    {"administrative": "花木", "datasSring": "datasSring", "data": []},
    {"administrative": "九亭", "datasSring": "datasSring", "data": []},
    {"administrative": "佘山", "datasSring": "datasSring", "data": []},
    {"administrative": "新桥", "datasSring": "datasSring", "data": []},
    {"administrative": "松江新城", "datasSring": "datasSring", "data": []},
    {"administrative": "莘闵别墅", "datasSring": "datasSring", "data": []},
    {"administrative": "松江老城", "datasSring": "datasSring", "data": []},
    {"administrative": "泗泾", "datasSring": "datasSring", "data": []},
    {"administrative": "车墩", "datasSring": "datasSring", "data": []},
    {"administrative": "共富", "datasSring": "datasSring", "data": []},
    {"administrative": "上大", "datasSring": "datasSring", "data": []},
    {"administrative": "杨行", "datasSring": "datasSring", "data": []},
    {"administrative": "大华", "datasSring": "datasSring", "data": []},
    {"administrative": "共康", "datasSring": "datasSring", "data": []},
    {"administrative": "庄行", "datasSring": "datasSring", "data": []},
    {"administrative": "柘林", "datasSring": "datasSring", "data": []},
    {"administrative": "江湾镇", "datasSring": "datasSring", "data": []},
    {"administrative": "临平路", "datasSring": "datasSring", "data": []},
    {"administrative": "曲阳", "datasSring": "datasSring", "data": []},
    {"administrative": "凉城", "datasSring": "datasSring", "data": []},
    {"administrative": "鲁迅公园", "datasSring": "datasSring", "data": []},
    {"administrative": "北外滩", "datasSring": "datasSring", "data": []},
    {"administrative": "不夜城", "datasSring": "datasSring", "data": []},
    {"administrative": "彭浦", "datasSring": "datasSring", "data": []},
    {"administrative": "西藏北路", "datasSring": "datasSring", "data": []},
    {"administrative": "阳城", "datasSring": "datasSring", "data": []},
    {"administrative": "闸北公园", "datasSring": "datasSring", "data": []},
    {"administrative": "永和", "datasSring": "datasSring", "data": []},
    {"administrative": "大宁", "datasSring": "datasSring", "data": []},
    {"administrative": "天山", "datasSring": "datasSring", "data": []},
    {"administrative": "光新", "datasSring": "datasSring", "data": []},
    {"administrative": "万里", "datasSring": "datasSring", "data": []},
    {"administrative": "长风", "datasSring": "datasSring", "data": []},
    {"administrative": "长寿路", "datasSring": "datasSring", "data": []},
    {"administrative": "松江大学城", "datasSring": "datasSring", "data": []},
    {"administrative": "吴泾", "datasSring": "datasSring", "data": []},
    {"administrative": "航华", "datasSring": "datasSring", "data": []},
    {"administrative": "静安新城", "datasSring": "datasSring", "data": []},
    {"administrative": "四团", "datasSring": "datasSring", "data": []},
    {"administrative": "武宁", "datasSring": "datasSring", "data": []},
    {"administrative": "曹家渡", "datasSring": "datasSring", "data": []},
    {"administrative": "江宁路", "datasSring": "datasSring", "data": []},
    {"administrative": "南京西路", "datasSring": "datasSring", "data": []},
    {"administrative": "静安寺", "datasSring": "datasSring", "data": []},
    {"administrative": "四川北路", "datasSring": "datasSring", "data": []},
    {"administrative": "外冈", "datasSring": "datasSring", "data": []},
    {"administrative": "菊园新区", "datasSring": "datasSring", "data": []},
    {"administrative": "徐行", "datasSring": "datasSring", "data": []},
    {"administrative": "徐汇滨江", "datasSring": "datasSring", "data": []},
    {"administrative": "盈浦", "datasSring": "datasSring", "data": []},
    {"administrative": "夏阳", "datasSring": "datasSring", "data": []},
    {"administrative": "徐泾", "datasSring": "datasSring", "data": []},
    {"administrative": "重固", "datasSring": "datasSring", "data": []},
    {"administrative": "朱家角", "datasSring": "datasSring", "data": []},
    {"administrative": "白鹤", "datasSring": "datasSring", "data": []},
    {"administrative": "赵巷", "datasSring": "datasSring", "data": []},
    {"administrative": "香花桥", "datasSring": "datasSring", "data": []},
    {"administrative": "联洋", "datasSring": "datasSring", "data": []},
    {"administrative": "华亭", "datasSring": "datasSring", "data": []},
    {"administrative": "新成路", "datasSring": "datasSring", "data": []},
    {"administrative": "青村", "datasSring": "datasSring", "data": []},
    {"administrative": "合庆", "datasSring": "datasSring", "data": []},
    {"administrative": "罗泾", "datasSring": "datasSring", "data": []},
    {"administrative": "高境", "datasSring": "datasSring", "data": []},
    {"administrative": "中远两湾城", "datasSring": "datasSring", "data": []},
    {"administrative": "老港镇", "datasSring": "datasSring", "data": []},
    {"administrative": "书院镇", "datasSring": "datasSring", "data": []},
    {"administrative": "打浦桥", "datasSring": "datasSring", "data": []},
    {"administrative": "五里桥", "datasSring": "datasSring", "data": []},
    {"administrative": "世博滨江", "datasSring": "datasSring", "data": []},
    {"administrative": "老西门", "datasSring": "datasSring", "data": []},
    {"administrative": "蓬莱公园", "datasSring": "datasSring", "data": []},
    {"administrative": "豫园", "datasSring": "datasSring", "data": []},
    {"administrative": "淮海中路", "datasSring": "datasSring", "data": []},
    {"administrative": "黄浦滨江", "datasSring": "datasSring", "data": []},
    {"administrative": "金泽", "datasSring": "datasSring", "data": []},
    {"administrative": "练塘", "datasSring": "datasSring", "data": []},
    {"administrative": "华新", "datasSring": "datasSring", "data": []},
    {"administrative": "南京东路", "datasSring": "datasSring", "data": []},
    {"administrative": "新天地", "datasSring": "datasSring", "data": []},
    {"administrative": "人民广场", "datasSring": "datasSring", "data": []},
    {"administrative": "董家渡", "datasSring": "datasSring", "data": []},
    {"administrative": "漕河泾", "datasSring": "datasSring", "data": []},
    {"administrative": "石化", "datasSring": "datasSring", "data": []},
    {"administrative": "廊下", "datasSring": "datasSring", "data": []},
    {"administrative": "金山", "datasSring": "datasSring", "data": []},
    {"administrative": "山阳", "datasSring": "datasSring", "data": []},
    {"administrative": "朱泾", "datasSring": "datasSring", "data": []},
    {"administrative": "枫泾", "datasSring": "datasSring", "data": []},
    {"administrative": "吕巷", "datasSring": "datasSring", "data": []},
    {"administrative": "亭林", "datasSring": "datasSring", "data": []},
    {"administrative": "张堰", "datasSring": "datasSring", "data": []},
    {"administrative": "马陆", "datasSring": "datasSring", "data": []},
    {"administrative": "小昆山", "datasSring": "datasSring", "data": []},
    {"administrative": "漕泾", "datasSring": "datasSring", "data": []},
    {"administrative": "叶榭", "datasSring": "datasSring", "data": []}]);

    useEffect(() => {
        let data = [];
        let date = '';
        //do not delete those commit
        if (shanghai.data && shanghai.data.length) {
            let splitData = setAdministrative(shanghai.data);
            splitData.forEach(item => {
                if (item.data.length) {
                    let {area, price, priceSign, datasSring, administrative} = insertData(item);
                    date = datasSring;
                    data.push(outliers(area, price, priceSign, datasSring, administrative));
                }
            });
            console.log(JSON.stringify({[date]: data}));
        }
    }, [shanghai.data]);
    // set administrative data for shanghai components
    const setAdministrative = (data) => {
        let datasSring = data[0].datasSring;
        let pureFlood = [{"administrative": "临港新城", "datasSring": datasSring, "data": []},
        {"administrative": "泥城镇", "datasSring": datasSring, "data": []},
        {"administrative": "万祥镇", "datasSring": datasSring, "data": []},
        {"administrative": "高东", "datasSring": datasSring, "data": []},
        {"administrative": "大团镇", "datasSring": datasSring, "data": []},
        {"administrative": "周浦", "datasSring": datasSring, "data": []},
        {"administrative": "塘桥", "datasSring": datasSring, "data": []},
        {"administrative": "金桥", "datasSring": datasSring, "data": []},
        {"administrative": "北蔡", "datasSring": datasSring, "data": []},
        {"administrative": "川沙", "datasSring": datasSring, "data": []},
        {"administrative": "惠南", "datasSring": datasSring, "data": []},
        {"administrative": "外高桥", "datasSring": datasSring, "data": []},
        {"administrative": "航头", "datasSring": datasSring, "data": []},
        {"administrative": "御桥", "datasSring": datasSring, "data": []},
        {"administrative": "源深", "datasSring": datasSring, "data": []},
        {"administrative": "杨东", "datasSring": datasSring, "data": []},
        {"administrative": "三林", "datasSring": datasSring, "data": []},
        {"administrative": "潍坊", "datasSring": datasSring, "data": []},
        {"administrative": "洋泾", "datasSring": datasSring, "data": []},
        {"administrative": "世博", "datasSring": datasSring, "data": []},
        {"administrative": "金杨", "datasSring": datasSring, "data": []},
        {"administrative": "碧云", "datasSring": datasSring, "data": []},
        {"administrative": "张江", "datasSring": datasSring, "data": []},
        {"administrative": "曹路", "datasSring": datasSring, "data": []},
        {"administrative": "宣桥", "datasSring": datasSring, "data": []},
        {"administrative": "高行", "datasSring": datasSring, "data": []},
        {"administrative": "新场", "datasSring": datasSring, "data": []},
        {"administrative": "曹杨", "datasSring": datasSring, "data": []},
        {"administrative": "长征", "datasSring": datasSring, "data": []},
        {"administrative": "真光", "datasSring": datasSring, "data": []},
        {"administrative": "真如", "datasSring": datasSring, "data": []},
        {"administrative": "桃浦", "datasSring": datasSring, "data": []},
        {"administrative": "甘泉宜川", "datasSring": datasSring, "data": []},
        {"administrative": "老闵行", "datasSring": datasSring, "data": []},
        {"administrative": "莘庄", "datasSring": datasSring, "data": []},
        {"administrative": "华漕", "datasSring": datasSring, "data": []},
        {"administrative": "金虹桥", "datasSring": datasSring, "data": []},
        {"administrative": "梅陇", "datasSring": datasSring, "data": []},
        {"administrative": "古美", "datasSring": datasSring, "data": []},
        {"administrative": "七宝", "datasSring": datasSring, "data": []},
        {"administrative": "颛桥", "datasSring": datasSring, "data": []},
        {"administrative": "浦江", "datasSring": datasSring, "data": []},
        {"administrative": "马桥", "datasSring": datasSring, "data": []},
        {"administrative": "春申", "datasSring": datasSring, "data": []},
        {"administrative": "龙柏", "datasSring": datasSring, "data": []},
        {"administrative": "金汇", "datasSring": datasSring, "data": []},
        {"administrative": "安亭", "datasSring": datasSring, "data": []},
        {"administrative": "嘉定新城", "datasSring": datasSring, "data": []},
        {"administrative": "南翔", "datasSring": datasSring, "data": []},
        {"administrative": "江桥", "datasSring": datasSring, "data": []},
        {"administrative": "嘉定老城", "datasSring": datasSring, "data": []},
        {"administrative": "丰庄", "datasSring": datasSring, "data": []},
        {"administrative": "康桥", "datasSring": datasSring, "data": []},
        {"administrative": "陆家嘴", "datasSring": datasSring, "data": []},
        {"administrative": "南码头", "datasSring": datasSring, "data": []},
        {"administrative": "祝桥", "datasSring": datasSring, "data": []},
        {"administrative": "周家嘴路", "datasSring": datasSring, "data": []},
        {"administrative": "控江路", "datasSring": datasSring, "data": []},
        {"administrative": "东外滩", "datasSring": datasSring, "data": []},
        {"administrative": "中原", "datasSring": datasSring, "data": []},
        {"administrative": "鞍山", "datasSring": datasSring, "data": []},
        {"administrative": "黄兴公园", "datasSring": datasSring, "data": []},
        {"administrative": "新江湾城", "datasSring": datasSring, "data": []},
        {"administrative": "五角场", "datasSring": datasSring, "data": []},
        {"administrative": "唐镇", "datasSring": datasSring, "data": []},
        {"administrative": "淞宝", "datasSring": datasSring, "data": []},
        {"administrative": "张庙", "datasSring": datasSring, "data": []},
        {"administrative": "顾村", "datasSring": datasSring, "data": []},
        {"administrative": "罗店", "datasSring": datasSring, "data": []},
        {"administrative": "月浦", "datasSring": datasSring, "data": []},
        {"administrative": "淞南", "datasSring": datasSring, "data": []},
        {"administrative": "大场镇", "datasSring": datasSring, "data": []},
        {"administrative": "通河", "datasSring": datasSring, "data": []},
        {"administrative": "新华路", "datasSring": datasSring, "data": []},
        {"administrative": "古北", "datasSring": datasSring, "data": []},
        {"administrative": "中山公园", "datasSring": datasSring, "data": []},
        {"administrative": "西郊", "datasSring": datasSring, "data": []},
        {"administrative": "北新泾", "datasSring": datasSring, "data": []},
        {"administrative": "仙霞", "datasSring": datasSring, "data": []},
        {"administrative": "镇宁路", "datasSring": datasSring, "data": []},
        {"administrative": "虹桥", "datasSring": datasSring, "data": []},
        {"administrative": "斜土路", "datasSring": datasSring, "data": []},
        {"administrative": "龙华", "datasSring": datasSring, "data": []},
        {"administrative": "康健", "datasSring": datasSring, "data": []},
        {"administrative": "建国西路", "datasSring": datasSring, "data": []},
        {"administrative": "徐家汇", "datasSring": datasSring, "data": []},
        {"administrative": "长桥", "datasSring": datasSring, "data": []},
        {"administrative": "植物园", "datasSring": datasSring, "data": []},
        {"administrative": "万体馆", "datasSring": datasSring, "data": []},
        {"administrative": "衡山路", "datasSring": datasSring, "data": []},
        {"administrative": "田林", "datasSring": datasSring, "data": []},
        {"administrative": "上海南站", "datasSring": datasSring, "data": []},
        {"administrative": "华泾", "datasSring": datasSring, "data": []},
        {"administrative": "华东理工", "datasSring": datasSring, "data": []},
        {"administrative": "南桥", "datasSring": datasSring, "data": []},
        {"administrative": "海湾", "datasSring": datasSring, "data": []},
        {"administrative": "奉城", "datasSring": datasSring, "data": []},
        {"administrative": "西渡", "datasSring": datasSring, "data": []},
        {"administrative": "奉贤金汇", "datasSring": datasSring, "data": []},
        {"administrative": "花木", "datasSring": datasSring, "data": []},
        {"administrative": "九亭", "datasSring": datasSring, "data": []},
        {"administrative": "佘山", "datasSring": datasSring, "data": []},
        {"administrative": "新桥", "datasSring": datasSring, "data": []},
        {"administrative": "松江新城", "datasSring": datasSring, "data": []},
        {"administrative": "莘闵别墅", "datasSring": datasSring, "data": []},
        {"administrative": "松江老城", "datasSring": datasSring, "data": []},
        {"administrative": "泗泾", "datasSring": datasSring, "data": []},
        {"administrative": "车墩", "datasSring": datasSring, "data": []},
        {"administrative": "共富", "datasSring": datasSring, "data": []},
        {"administrative": "上大", "datasSring": datasSring, "data": []},
        {"administrative": "杨行", "datasSring": datasSring, "data": []},
        {"administrative": "大华", "datasSring": datasSring, "data": []},
        {"administrative": "共康", "datasSring": datasSring, "data": []},
        {"administrative": "庄行", "datasSring": datasSring, "data": []},
        {"administrative": "柘林", "datasSring": datasSring, "data": []},
        {"administrative": "江湾镇", "datasSring": datasSring, "data": []},
        {"administrative": "临平路", "datasSring": datasSring, "data": []},
        {"administrative": "曲阳", "datasSring": datasSring, "data": []},
        {"administrative": "凉城", "datasSring": datasSring, "data": []},
        {"administrative": "鲁迅公园", "datasSring": datasSring, "data": []},
        {"administrative": "北外滩", "datasSring": datasSring, "data": []},
        {"administrative": "不夜城", "datasSring": datasSring, "data": []},
        {"administrative": "彭浦", "datasSring": datasSring, "data": []},
        {"administrative": "西藏北路", "datasSring": datasSring, "data": []},
        {"administrative": "阳城", "datasSring": datasSring, "data": []},
        {"administrative": "闸北公园", "datasSring": datasSring, "data": []},
        {"administrative": "永和", "datasSring": datasSring, "data": []},
        {"administrative": "大宁", "datasSring": datasSring, "data": []},
        {"administrative": "天山", "datasSring": datasSring, "data": []},
        {"administrative": "光新", "datasSring": datasSring, "data": []},
        {"administrative": "万里", "datasSring": datasSring, "data": []},
        {"administrative": "长风", "datasSring": datasSring, "data": []},
        {"administrative": "长寿路", "datasSring": datasSring, "data": []},
        {"administrative": "松江大学城", "datasSring": datasSring, "data": []},
        {"administrative": "吴泾", "datasSring": datasSring, "data": []},
        {"administrative": "航华", "datasSring": datasSring, "data": []},
        {"administrative": "静安新城", "datasSring": datasSring, "data": []},
        {"administrative": "四团", "datasSring": datasSring, "data": []},
        {"administrative": "武宁", "datasSring": datasSring, "data": []},
        {"administrative": "曹家渡", "datasSring": datasSring, "data": []},
        {"administrative": "江宁路", "datasSring": datasSring, "data": []},
        {"administrative": "南京西路", "datasSring": datasSring, "data": []},
        {"administrative": "静安寺", "datasSring": datasSring, "data": []},
        {"administrative": "四川北路", "datasSring": datasSring, "data": []},
        {"administrative": "外冈", "datasSring": datasSring, "data": []},
        {"administrative": "菊园新区", "datasSring": datasSring, "data": []},
        {"administrative": "徐行", "datasSring": datasSring, "data": []},
        {"administrative": "徐汇滨江", "datasSring": datasSring, "data": []},
        {"administrative": "盈浦", "datasSring": datasSring, "data": []},
        {"administrative": "夏阳", "datasSring": datasSring, "data": []},
        {"administrative": "徐泾", "datasSring": datasSring, "data": []},
        {"administrative": "重固", "datasSring": datasSring, "data": []},
        {"administrative": "朱家角", "datasSring": datasSring, "data": []},
        {"administrative": "白鹤", "datasSring": datasSring, "data": []},
        {"administrative": "赵巷", "datasSring": datasSring, "data": []},
        {"administrative": "香花桥", "datasSring": datasSring, "data": []},
        {"administrative": "联洋", "datasSring": datasSring, "data": []},
        {"administrative": "华亭", "datasSring": datasSring, "data": []},
        {"administrative": "新成路", "datasSring": datasSring, "data": []},
        {"administrative": "青村", "datasSring": datasSring, "data": []},
        {"administrative": "合庆", "datasSring": datasSring, "data": []},
        {"administrative": "罗泾", "datasSring": datasSring, "data": []},
        {"administrative": "高境", "datasSring": datasSring, "data": []},
        {"administrative": "中远两湾城", "datasSring": datasSring, "data": []},
        {"administrative": "老港镇", "datasSring": datasSring, "data": []},
        {"administrative": "书院镇", "datasSring": datasSring, "data": []},
        {"administrative": "打浦桥", "datasSring": datasSring, "data": []},
        {"administrative": "五里桥", "datasSring": datasSring, "data": []},
        {"administrative": "世博滨江", "datasSring": datasSring, "data": []},
        {"administrative": "老西门", "datasSring": datasSring, "data": []},
        {"administrative": "蓬莱公园", "datasSring": datasSring, "data": []},
        {"administrative": "豫园", "datasSring": datasSring, "data": []},
        {"administrative": "淮海中路", "datasSring": datasSring, "data": []},
        {"administrative": "黄浦滨江", "datasSring": datasSring, "data": []},
        {"administrative": "金泽", "datasSring": datasSring, "data": []},
        {"administrative": "练塘", "datasSring": datasSring, "data": []},
        {"administrative": "华新", "datasSring": datasSring, "data": []},
        {"administrative": "南京东路", "datasSring": datasSring, "data": []},
        {"administrative": "新天地", "datasSring": datasSring, "data": []},
        {"administrative": "人民广场", "datasSring": datasSring, "data": []},
        {"administrative": "董家渡", "datasSring": datasSring, "data": []},
        {"administrative": "漕河泾", "datasSring": datasSring, "data": []},
        {"administrative": "石化", "datasSring": datasSring, "data": []},
        {"administrative": "廊下", "datasSring": datasSring, "data": []},
        {"administrative": "金山", "datasSring": datasSring, "data": []},
        {"administrative": "山阳", "datasSring": datasSring, "data": []},
        {"administrative": "朱泾", "datasSring": datasSring, "data": []},
        {"administrative": "枫泾", "datasSring": datasSring, "data": []},
        {"administrative": "吕巷", "datasSring": datasSring, "data": []},
        {"administrative": "亭林", "datasSring": datasSring, "data": []},
        {"administrative": "张堰", "datasSring": datasSring, "data": []},
        {"administrative": "马陆", "datasSring": datasSring, "data": []},
        {"administrative": "小昆山", "datasSring": datasSring, "data": []},
        {"administrative": "漕泾", "datasSring": datasSring, "data": []},
        {"administrative": "叶榭", "datasSring": datasSring, "data": []}];
        let flood = [];
        data.forEach(element => {
            flood.push(element.flood);
            pureFlood.forEach(item => {
                if (element.flood === item.administrative) {
                    item.data.push(element);
                }
            });
        });
        // console.log(template([...new Set(flood)]));
        setPureFlood(pureFlood);
        return pureFlood;
    };

    let choseAdministrative = (administrative) => {
        setAdministrativeByChoice(administrative);
    };

    diffValueOfPrice(weekIncreaseShanghai);

    return (
        <div className="xc-histogram-dash">
            <div className='xc-histogram-dash-shanghai'>
                {pureFlood.map(item => <span key={item.administrative}><Button type={administrative === item.administrative ? 'primary' : ''} onClick={() => choseAdministrative(item.administrative)}> {item.administrative}</Button></span>)}
            </div>
            <WeekIncrease administrative={administrative} weekIncrease={weekIncreaseShanghai} />
        </div>
    );
}
